estimator/urls.py
from django.urls import path
from . import views

app_name = 'estimator'

urlpatterns = [
    path('', views.estimator, name ='estimator_page'),
    path('estimate/', views.estimate_chances, name = 'submit_estimation'),
    path('results/', views.view_results, name='results'),

]

medical_cost_estimator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('estimator.urls', namespace='estimate'))
]

estimator/models.py
from django.db import models

class PredResults(models.Model):
    age = models.IntegerField()
    bmi = models.FloatField()
    children = models.IntegerField()
    sex_female = models.IntegerField()
    sex_male = models.IntegerField()
    smoke_no = models.IntegerField()
    smoke_yes = models.IntegerField()
    charges = models.FloatField()

    def __str__(self):
        return self.charges

estimator/views.py
from django.shortcuts import render
from django.http import JsonResponse
from . models import PredResults
import pandas as pd



def estimator(request):
    return render(request, 'estimate.html')


def estimate_chances(request):

    if request.POST.get('action') == 'post':

        age=int(request.POST.get('age'))
        bmi=float(request.POST.get('bmi'))
        children=int(request.POST.get('children'))
        sex_female=int(request.POST.get('sex_female'))
        sex_male=int(request.POST.get('sex_male'))
        smoke_no=int(request.POST.get('smoke_no'))
        smoke_yes=int(request.POST.get('smoke_yes'))

        model = pd.read_pickle('/Users/jordanmoore/Desktop/DS/healthcare_cost_prediction/new_model.pickle') 

        result = model.predict([[age, bmi, children, sex_female, sex_male, smoke_no, smoke_yes]])

        charges = result[0]

        PredResults.objects.create(age=age, bmi=bmi, children=children, sex_female=sex_female, sex_male=sex_male, smoke_no=smoke_no, smoke_yes=smoke_yes, charges=charges)

        return JsonResponse({'result': charges, 'age': age, 'bmi': bmi, 'children': children, 'sex_female': sex_female, 'sex_male': sex_male, 'smoke_no': smoke_no, 'smoke_yes': smoke_yes}, safe=False)

def view_results(request):
    data = {'dataset': PredResults.objects.all()}
    return render(request, 'results.html', data)

estimator/templates/base.html
<!doctype html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>Medical Cost Prediction</title>
    
            <style> 
                   .btn {
                    background-color: #ff9240;
                    color: white;
                    border-color: white;
                   }
                   .nav-link {
                       color: black;
                   }

                   .style {
                       background-color: #296a6e;
                       color: black;
                   }
            </style>

    </head>
    
    <body>
    <div class='navigation'>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/" style= "color: rgb(46, 44, 44)">Estimation <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/results" style= "color: rgb(46, 44, 44)" >Query Database</a>
                </li>
            </ul>
        </div>
    </nav>
</div>

    {% block main %}
    {% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

estimator/templates/estimate.html
{% extends "base.html" %}

{% block main %}
<!-- Modal -->
<div class='style'>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Estimation Results</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Prediction Input:</h5>
                <div>Age: <span id="ag"></span></div>
                <div>BMI: <span id="bm"></span></div>
                <div>Number of Children: <span id="ch"></span></div>
                <div>If female insert 1 if male insert 0: <span id="sf"></span></div>
                <div>If male insert 1 if female insert 0: <span id="sm"></span></div>
                <div>If non-smoker insert 1 if smoker insert 0: <span id="sn"></span></div>
                <div>If smoker insert 1 if non-smoker insert 0: <span id="sy"></span></div>
                <h5 class="pt-3">Prediction Charges:</h5>
                <div id="estimation"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="/results" role="button">View DB</a>
            </div>
        </div>
    </div>
</div>

<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            <h1>Medical Expenditure Prediction</h1>
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="age">Age</label>
                    <input type="number" class="form-control" id="age" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="bmi">BMI</label>
                    <input type="number" step="0.111" class="form-control" id="bmi" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="children">Number of Children</label>
                    <input type="number" class="form-control" id="children" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="sex_female">If female insert 1 if male insert 0</label>
                    <input type="number" class="form-control" id="sex_female" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="sex_male">If male insert 1 if female insert 0 </label>
                    <input type="number" class="form-control" id="sex_male" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="smoke_no">If non-smoker insert 1 if smoker insert 0</label>
                    <input type="number" class="form-control" id="smoke_no" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="smoke_yes">If smoker insert 1 if non-smoker insert 0 </label>
                    <input type="number" class="form-control" id="smoke_yes" placeholder="" required>
                </div>
                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" style="margin-bottom: 5%";>Submit</button>
            </form>
        </div>
    </div>
</div>
</div>
<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "estimate:submit_estimation" %}',
            data:{
                age:$('#age').val(),
                bmi:$('#bmi').val(),
                children:$('#children').val(),
                sex_female:$('#sex_female').val(),
                sex_male:$('#sex_male').val(),
                smoke_no:$('#smoke_no').val(),
                smoke_yes:$('#smoke_yes').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"].reset();
                document.getElementById("estimation").innerHTML = json['result']
                document.getElementById("ag").innerHTML = json['age']
                document.getElementById("bm").innerHTML = json['bmi']
                document.getElementById("ch").innerHTML = json['children']
                document.getElementById("sf").innerHTML = json['sex_female']
                document.getElementById("sm").innerHTML = json['sex_male']
                document.getElementById("sn").innerHTML = json['smoke_no']
                document.getElementById("sy").innerHTML = json['smoke_yes']
            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>

{% endblock %}

estimator/templates/results.html
{% extends "base.html" %}

{% block main %}
    <div class="container pt-5">
        <div class="row">

        <h1>Forecasting Results</h1>

            <table class="table">
                <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Age</th>
                <th scope="col">BMI</th>
                <th scope="col">Number of Children</th>
                <th scope="col">Female</th>
                <th scope="col">Male</th>
                <th scope="col">Non-Smoker</th>
                <th scope="col">Smoker</th>
                <th scope="col">Prediction</th>
                </tr>
                </thead>
                <tbody>
                {% for data in dataset %}
                    <tr>
                    <th scope="row">{{ data.id }}</th>
                    <td>{{ data.age }}</td>
                    <td>{{ data.bmi }}</td>
                    <td>{{ data.children }}</td>
                    <td>{{ data.sex_female }}</td>
                    <td>{{ data.sex_male }}</td>
                    <td>{{ data.smoke_no }}</td>
                    <td>{{ data.smoke_yes }}</td>
                    <td>{{ data.charges }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}